import { requireAuth } from '../middleware/auth.js';

/**
 * GET /v1/threads/:threadId/conflicts — polling endpoint for detected
 * conflicts.
 *
 * The durable source of truth for anomaly/conflict notifications.
 * Webhook delivery (see modules/webhooks/webhook-delivery.js) can fail
 * silently — wrong URL, receiver down, network blip — with no built-in
 * way for the caller to know delivery didn't happen. This endpoint
 * always reflects ground truth regardless of webhook delivery status,
 * matching standard practice for production webhook systems (Stripe,
 * GitHub, etc. all pair push delivery with a pollable/listable source
 * of truth).
 *
 * SECURITY FIX (post-review, addresses P0 finding): conflicts are now
 * filtered per-caller. A conflict summary is generated by the LLM from
 * the full plaintext payload of both claims, which means it can leak
 * content the caller has no read access to via RECALL. This endpoint
 * now evaluates authorizationPolicy.evaluate() against BOTH claims in
 * a conflict before returning the summary. If the caller lacks read
 * access to either side, the conflict is either omitted entirely (if
 * they can't read either claim) or returned with summary/scores
 * stripped (if they can read one but not the other) — the caller
 * learns a conflict exists on this thread, but not its content, which
 * mirrors RECALL's own PERMISSION_DENIED semantics (entryExists: true,
 * no content leak).
 *
 * @param {import('fastify').FastifyInstance} fastify
 * @param {{claimStore, identityProvider, authorizationPolicy}} opts
 */
export default async function conflictsRoutes(fastify, opts) {
  const { claimStore, identityProvider, authorizationPolicy } = opts;

  fastify.get(
    '/v1/threads/:threadId/conflicts',
    { preHandler: requireAuth(identityProvider) },
    async (request) => {
      const { threadId } = request.params;
      const requesterIdentity = request.identity;

      const conflicts = await claimStore.listConflictsInThread(threadId);

      const filtered = await Promise.all(
        conflicts.map(async (c) => {
          const [claimA, claimB] = await Promise.all([
            claimStore.getById(c.claimId),
            claimStore.getById(c.conflictsWithClaimId),
          ]);

          // If either claim was hard-deleted (shouldn't happen — claims
          // are soft-revoked, not deleted) treat as no access.
          if (!claimA || !claimB) {
            return null;
          }

          const [decisionA, decisionB] = await Promise.all([
            authorizationPolicy.evaluate({ claim: claimA, requesterIdentity, action: 'read' }),
            authorizationPolicy.evaluate({ claim: claimB, requesterIdentity, action: 'read' }),
          ]);

          const canReadBoth = decisionA.allowed && decisionB.allowed;

          if (!decisionA.allowed && !decisionB.allowed) {
            return null; // omit — caller can't read either side
          }

          if (canReadBoth) {
            return {
              conflict_id: c.conflictId,
              claim_id: c.claimId,
              conflicts_with_claim_id: c.conflictsWithClaimId,
              similarity_score: c.similarityScore,
              summary: c.summary,
              status: c.status,
              detected_at: c.detectedAt.toISOString(),
            };
          }

          // Caller can read exactly one side — confirm the conflict
          // exists without leaking the summary (which was generated
          // from both claims' plaintext payloads) or the score.
          return {
            conflict_id: c.conflictId,
            claim_id: c.claimId,
            conflicts_with_claim_id: c.conflictsWithClaimId,
            similarity_score: null,
            summary: null,
            status: c.status,
            detected_at: c.detectedAt.toISOString(),
            note: 'PARTIAL_ACCESS — you do not have read access to one side of this conflict; summary withheld',
          };
        })
      );

      return {
        conflicts: filtered.filter((c) => c !== null),
      };
    }
  );
}